# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-01-11 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('distance', models.FloatField(blank=True, default=None, null=True)),
                ('time_taken', models.DurationField(blank=True, default=None, null=True)),
                ('repetitions', models.IntegerField(blank=True, default=None, null=True)),
                ('set_number', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type_of_exercise', models.CharField(choices=[('cardio', 'CARDIO'), ('strength', 'STRENGTH'), ('flexibility', 'FLEXIBILITY')], max_length=251)),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'db_table': 'exercise',
            },
        ),
        migrations.AddField(
            model_name='activities',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnesstracker.Exercise'),
        ),
    ]
